### ISSUE TITLE
Impact-45 Attachments

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#11]
Short Mag. increases damage.
![payday2_win32_release_2020-08-08_13-48-48](https://user-images.githubusercontent.com/23544898/89716877-ba203100-d97e-11ea-9809-38dcc66cf4d7.png)

Silent Gear suppressor lacks description.
![payday2_win32_release_2020-08-08_13-48-34](https://user-images.githubusercontent.com/23544898/89716878-bb515e00-d97e-11ea-84ee-05365529716f.png)

**Comment by HugoZink** [comment]
[The short magazine increasing damage is apparently intentional.](https://github.com/HugoZink/IreNFist/blob/master/IRE%20AND%20FIST%20REBORN/lua/wpn_parts.lua#L2760) It's probably intended to be similar to the Compact-5's 10mm rounds.

Not every weapon mod is intended to have a description, but I will try my best to add them.
