### ISSUE TITLE
No Zeal Shotgunners

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#31]
friend I was playing with came to the realization that none of the Zeal units we came across had shotguns despite vanilla payday 2 having them.

**Comment by HugoZink** [comment]
I don't really play DS so this might have slipped under my radar. I don't think I'm removing any units or squads though. We'll see.

**Comment by HugoZink** [comment]
Are you **positive** that vanilla DS has shotgunners? You might want to check again. The game files quite literally don't *have* any ZEAL shotgunners defined. They literally do not have a unit for it.

**Comment by HugoZink** [comment]
I got confirmation that ZEAL shotgunners straight up don't exist. I'll leave the issue open because I do actually want to add this properly.

**Comment by HugoZink** [comment]
Oh cool, I got it working. In the next update, ZEAL shotgunners should exist again.

I wanted to add an Akimbo cop too, but sadly I can't do that without restricting the mod to friends-only. There is akimbo code in the game but it's broken (and isn't loaded by default).

Either way it'll make its way into the game. I now also have the freedom to give more different weapons to different squads, though since I'm restricted to only weapon units that are in the base game _and_ are loaded, the usage is a little limited.

**Comment by Bwamo** [comment]
Oh. I wasn't really too sure on the information and probs should've done some proper research beforehand, but at least some framework enhancement came out of it, I suppose. soz about that

**Comment by HugoZink** [comment]
Nah don't worry, if you hadn't reported this issue I literally wouldn't have known about it.
