### ISSUE TITLE
ADS bug on Locomotive Shotgun or Super Shorty equipped with a stock

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#41]
I've only tested with two different stocks, but it's likely to happen with every stock. Other weapons, such as assault rifles seem to be unaffected.

Ultor Stock:
![payday2_win32_release_hi2lb9gVqe](https://user-images.githubusercontent.com/71377805/93511450-0af75200-f94d-11ea-8589-bd642c0f76a9.png)

Also, some stocks and magazines don't increase stats on some weapons--was this intentional?

**Comment by HugoZink** [comment]
I have no idea why this happens, but the same thing happens on the Ithaca with some stocks, where you're looking into your own hand. I'll check it out.

And yes, a lot of weapon mods don't affect stats, which was intentional. This mod is balanced around sane base stats with maybe a compensator and longer barrel on top.

**Comment by HugoZink** [comment]
Fixed.
