### ISSUE TITLE
Possible incompatibility with Narrator Anticipation/Vocal Heisters mod

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#48]
Bain's warnings about the incoming assault can be inaccurate sometimes; The assault can start before the 30 seconds mark. I'm not entirely sure if this is caused by the Narrator Anticipation mod or IREnFist mod. But It's likely just an incompatibility since the former wasn't meant for the latter that changes how the assault works.

This seemed to occur on specific heists such as Golden Grin Casino on Death Sentence.

I will provide proof as soon as possible.

**Comment by HugoZink** [comment]
This is caused by the game skipping assault anticipations somewhat randomly. There's actually a whole lot going on under the hood there, but rest assured this isn't InF's fault. InF doesn't change the way anticipation works, it just changes the delay between an assault ending and anticipation starting.

Basically, there's a bunch of factors that can either shorten or remove the anticipation delay, one of which is "drama". If someone gets downed or heavily damaged during the assault anticipation, the cops can decide to suddenly rush in and immediately start the assault. This is the same mechanic that can prolong assaults that are supposed to be fading.

There's a lot of factors, some of which are unknown, and some of which might definitely be broken (another factor is the captain, anticipation gets really iffy right before the captain arrives, and right after he's killed). I can't fix this on my end. If you removed InF the issue would still happen. It's just more noticeable with Vocal Heisters because the anticipation delay is actually announced. Even without the announcement, you could tell by the music.
