### ISSUE TITLE
PP-19-01 Vityaz - ammo type with vanilla stats

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#51]
_And another one_
![20200926165453_1](https://user-images.githubusercontent.com/34880333/94342633-fa18a180-001a-11eb-9b6e-d6ce0aa9a432.jpg)

I wonder what should be done with this. Maybe deepclone it?

**Comment by HugoZink** [comment]
Thanks, fixed for the next release.

Word of warning: I am likely to drop support for this author's weapon mods (the weapons themselves will still be supported). He changes the stats and the weaponmod internal names around really often, which not only breaks people's existing weapon setups, it also causes InF to crash.

The reason this updated fork of InF crashed so much in the early days was 99% caused by these weapons. If I decide to slow down development at some point in the future, I'd rather have an unsupported weapon mod or two rather than a full-on crash.

**Comment by MrVavlo** [comment]
Oh, that's okay. 
BTW, since I don't review those weapons that was hidden/deleted on MWS, I noticed how many of them are from this author on that list, so this's not a big issue.

**Comment by HugoZink** [comment]
Fix released.
