### ISSUE TITLE
Charm Stats

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#7]
Not sure if this is intended, but all charms are the 3% XP/Money Reward Team Boost.
![payday2_win32_release_2020-07-27_12-11-18](https://user-images.githubusercontent.com/23544898/88565224-4b4beb00-d002-11ea-93e3-e86479f2528b.png)

**Comment by HugoZink** [comment]
This is intentional. Instead of making every gun as minmax-y as possible, there are now only a select few parts which actually change the weapon's stats in a meaningful way (such as barrels and ammunition).

If anyone has suggestions on a better way to deal with these, feel free to drop me a suggestion.
