### ISSUE TITLE
[Performance issue]

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#87]
Apparently, I noticed a huge performance drop on FWB as well, and this only happened during assaults; The FPS went back to normal (60) during assault breaks.

(The same issue still persists on Diamond Heist, but it's not like I play that heist anyway.)

**Comment by artemisexe** [comment]
I know I have a weak PC, but I still hope you can fix, if not optimize, it further; having low fps during assaults means I would need to finish the said maps in stealth.

**Comment by artemisexe** [comment]
For the record, I have the Think Faster option enabled, but I have set it to the minimum. This also seems to happen on specific maps; In No Mercy heist, I don't have any performance issues whatsoever.

**Comment by HugoZink** [comment]
What exactly is the minimum value in InF? I set it to 60 in Think Faster, but it might still be 120 in DH and FWB. For some reason these two heists cause immense performance drops. If my theory is correct, you should see the same immense performance drops in Mallcrasher.

I strongly recommend installing Think Faster, as it takes precedence over InF and allows you to set these heists to lower throughput values. I also _slightly_ more optimized a few smaller things in Think Faster that I haven't pushed back into InF yet.

**Comment by artemisexe** [comment]
It's 60 in InF. I don't have the standalone Think Faster (yet); I'll consider installing it soon.

And yeah, I also did notice a huge performance drop in Mallcrasher.

**Comment by artemisexe** [comment]
Though, I'm quite confused about editing the values:
![image](https://user-images.githubusercontent.com/71377805/98445173-bef4ac80-2148-11eb-807f-311cf742703d.png)

How do specifically edit those heists? I've checked the core lua, but I don't see FWB there.

**Comment by HugoZink** [comment]
The menu would get very messy if I auto-generated sliders for every heist, so I grouped them together into groups totally subjectively.

I haven't categorized FWB yet, but mallcrasher is in the "very badly optimized" category.

**Comment by artemisexe** [comment]
edited message

**Comment by artemisexe** [comment]
Thanks for the heads up. My FPS on Mallcrasher is far better with the Think Faster mod. I set the values to 98 and 75 for badly and very badly heists, respectively. I have yet to test it on Diamond Heist or FWB.

**Comment by artemisexe** [comment]
There's a bit of fps boost with the minimum tailored value (60-75) on DH, but it's still beyond playable. The fps dropped immensely 3 minutes after the alarm has been triggered, but then I gained (more) fps during assault breaks/have 60 fps in stealth.

**Comment by HugoZink** [comment]
Well sadly there just isn't much I can do about this. Think Faster limited to 60 should give a marginal increase in performance, but other than that InF simply does not touch the cop AI in any meaningful enough way to cause performance drops like these. It might be misbehaving with some other mod but who knows? It's more likely that these maps have badly set-up culling and the game tries to render too many cop models at once.

Since there aren't any performance profiling tools for this game, it's not possible for me to fix this properly. Most of the game's performance issues are in parts of the game we as modders cannot touch without editing the heists themselves (which would cause a lot of other issues).

I'll have to close this for now, since Think Faster is the only optimization I'll be able to perform.
