### ISSUE TITLE
[Bug] Longer/shorter reload time resets to normal rate after equipping any attachment/loading the heist.

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#91]
**Ok, I hope that isn't vanilla issue, so this post will have any point to exist.**

As I know, any high-size magazine will increase reload time, and vice versa. 
But that change right now will be erased after further modification.
(Reproduced on Akimbo Shadow Tacticals, but the weapon/attachments doesn't really matter)
![20201110115009_1](https://user-images.githubusercontent.com/34880333/98651809-c506ab00-234b-11eb-9630-d3c2642c1920.jpg)
On this screenshot, game shows that equipping this magazine will increase reload time to 3.6 secs, despite being already equipped (stat doesn't turns red/green on equipped attachments).
![20201110115303_1](https://user-images.githubusercontent.com/34880333/98651816-c6d06e80-234b-11eb-8e3c-955d639c2004.jpg)
_Yes, I just equipped the charm as example and it threw away magazine' changes on reload time back to 2 secs._

The worst part is that I can't check if it _actually_ change the reload time in-game... since loading into any heist will reset reload time too.

### Since I've issued false calls before here, just to be careful: 
I would like to know if anyone else experienced this as well, if it's not only happens on my end.

**Comment by MrVavlo** [comment]
~~Also, wait, why there's "+10 dmg falloff" text on magazines?~~

**Comment by HugoZink** [comment]
This _might_ be a WeaponLib issue, or a mod compatibility issue. The blackmarket stats window is absolutely horrible to work with and very error-prone. Similarly this is why you might see a +0 reload time on totally random attachments.

I know for sure that it works ingame, since the Beretta reload becomes _way_ slower.

As for these pistols, these might not be fully compatible or compatibility might be outdated, which could cause weird results on some weaponmods (such as damage falloff text).

**Comment by HugoZink** [comment]
This is not fixable on my end while InF is reliant on WeaponLib.
